# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='hakuraku',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x08hakuraku\"\x88\x02\n\nUMDatabase\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x1e\n\x05\x63hara\x18\x02 \x03(\x0b\x32\x0f.hakuraku.Chara\x12\x39\n\x13succession_relation\x18\x03 \x03(\x0b\x32\x1c.hakuraku.SuccessionRelation\x12-\n\rrace_instance\x18\x04 \x03(\x0b\x32\x16.hakuraku.RaceInstance\x12)\n\x0bwins_saddle\x18\x05 \x03(\x0b\x32\x14.hakuraku.WinsSaddle\x12\x34\n\x11special_case_race\x18\x06 \x03(\x0b\x32\x19.hakuraku.SpecialCaseRace\"4\n\x05\x43hara\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcast_name\x18\x03 \x01(\t\"\\\n\x12SuccessionRelation\x12\x15\n\rrelation_type\x18\x01 \x01(\x05\x12\x16\n\x0erelation_point\x18\x02 \x01(\x05\x12\x17\n\x0fmember_chara_id\x18\x03 \x03(\x05\"(\n\x0cRaceInstance\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"d\n\nWinsSaddle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10race_instance_id\x18\x03 \x03(\x05\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x10\n\x08group_id\x18\x05 \x01(\x05\"\x9a\x02\n\x0fSpecialCaseRace\x12\x18\n\x10race_instance_id\x18\x01 \x01(\x05\x12\x15\n\rprogram_group\x18\x02 \x01(\x05\x12\x41\n\x0frace_permission\x18\x03 \x01(\x0e\x32(.hakuraku.SpecialCaseRace.RacePermission\x12\x10\n\x08\x63hara_id\x18\x04 \x03(\x05\"\x80\x01\n\x0eRacePermission\x12\x1b\n\x17UNKNOWN_RACE_PERMISSION\x10\x00\x12\x0e\n\nFIRST_YEAR\x10\x01\x12\x0f\n\x0bSECOND_YEAR\x10\x02\x12\x18\n\x14SECOND_OR_THIRD_YEAR\x10\x03\x12\x0e\n\nTHIRD_YEAR\x10\x04\x12\x06\n\x02\x45X\x10\x05'
)



_SPECIALCASERACE_RACEPERMISSION = _descriptor.EnumDescriptor(
  name='RacePermission',
  full_name='hakuraku.SpecialCaseRace.RacePermission',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_RACE_PERMISSION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FIRST_YEAR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECOND_YEAR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECOND_OR_THIRD_YEAR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THIRD_YEAR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EX', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=738,
  serialized_end=866,
)
_sym_db.RegisterEnumDescriptor(_SPECIALCASERACE_RACEPERMISSION)


_UMDATABASE = _descriptor.Descriptor(
  name='UMDatabase',
  full_name='hakuraku.UMDatabase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='hakuraku.UMDatabase.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chara', full_name='hakuraku.UMDatabase.chara', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='succession_relation', full_name='hakuraku.UMDatabase.succession_relation', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='race_instance', full_name='hakuraku.UMDatabase.race_instance', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wins_saddle', full_name='hakuraku.UMDatabase.wins_saddle', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='special_case_race', full_name='hakuraku.UMDatabase.special_case_race', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=289,
)


_CHARA = _descriptor.Descriptor(
  name='Chara',
  full_name='hakuraku.Chara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hakuraku.Chara.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='hakuraku.Chara.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cast_name', full_name='hakuraku.Chara.cast_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=343,
)


_SUCCESSIONRELATION = _descriptor.Descriptor(
  name='SuccessionRelation',
  full_name='hakuraku.SuccessionRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='relation_type', full_name='hakuraku.SuccessionRelation.relation_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relation_point', full_name='hakuraku.SuccessionRelation.relation_point', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='member_chara_id', full_name='hakuraku.SuccessionRelation.member_chara_id', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=437,
)


_RACEINSTANCE = _descriptor.Descriptor(
  name='RaceInstance',
  full_name='hakuraku.RaceInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hakuraku.RaceInstance.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='hakuraku.RaceInstance.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=479,
)


_WINSSADDLE = _descriptor.Descriptor(
  name='WinsSaddle',
  full_name='hakuraku.WinsSaddle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hakuraku.WinsSaddle.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='hakuraku.WinsSaddle.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='race_instance_id', full_name='hakuraku.WinsSaddle.race_instance_id', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='hakuraku.WinsSaddle.priority', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='hakuraku.WinsSaddle.group_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=581,
)


_SPECIALCASERACE = _descriptor.Descriptor(
  name='SpecialCaseRace',
  full_name='hakuraku.SpecialCaseRace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='race_instance_id', full_name='hakuraku.SpecialCaseRace.race_instance_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='program_group', full_name='hakuraku.SpecialCaseRace.program_group', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='race_permission', full_name='hakuraku.SpecialCaseRace.race_permission', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chara_id', full_name='hakuraku.SpecialCaseRace.chara_id', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPECIALCASERACE_RACEPERMISSION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=866,
)

_UMDATABASE.fields_by_name['chara'].message_type = _CHARA
_UMDATABASE.fields_by_name['succession_relation'].message_type = _SUCCESSIONRELATION
_UMDATABASE.fields_by_name['race_instance'].message_type = _RACEINSTANCE
_UMDATABASE.fields_by_name['wins_saddle'].message_type = _WINSSADDLE
_UMDATABASE.fields_by_name['special_case_race'].message_type = _SPECIALCASERACE
_SPECIALCASERACE.fields_by_name['race_permission'].enum_type = _SPECIALCASERACE_RACEPERMISSION
_SPECIALCASERACE_RACEPERMISSION.containing_type = _SPECIALCASERACE
DESCRIPTOR.message_types_by_name['UMDatabase'] = _UMDATABASE
DESCRIPTOR.message_types_by_name['Chara'] = _CHARA
DESCRIPTOR.message_types_by_name['SuccessionRelation'] = _SUCCESSIONRELATION
DESCRIPTOR.message_types_by_name['RaceInstance'] = _RACEINSTANCE
DESCRIPTOR.message_types_by_name['WinsSaddle'] = _WINSSADDLE
DESCRIPTOR.message_types_by_name['SpecialCaseRace'] = _SPECIALCASERACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UMDatabase = _reflection.GeneratedProtocolMessageType('UMDatabase', (_message.Message,), {
  'DESCRIPTOR' : _UMDATABASE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:hakuraku.UMDatabase)
  })
_sym_db.RegisterMessage(UMDatabase)

Chara = _reflection.GeneratedProtocolMessageType('Chara', (_message.Message,), {
  'DESCRIPTOR' : _CHARA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:hakuraku.Chara)
  })
_sym_db.RegisterMessage(Chara)

SuccessionRelation = _reflection.GeneratedProtocolMessageType('SuccessionRelation', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSIONRELATION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:hakuraku.SuccessionRelation)
  })
_sym_db.RegisterMessage(SuccessionRelation)

RaceInstance = _reflection.GeneratedProtocolMessageType('RaceInstance', (_message.Message,), {
  'DESCRIPTOR' : _RACEINSTANCE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:hakuraku.RaceInstance)
  })
_sym_db.RegisterMessage(RaceInstance)

WinsSaddle = _reflection.GeneratedProtocolMessageType('WinsSaddle', (_message.Message,), {
  'DESCRIPTOR' : _WINSSADDLE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:hakuraku.WinsSaddle)
  })
_sym_db.RegisterMessage(WinsSaddle)

SpecialCaseRace = _reflection.GeneratedProtocolMessageType('SpecialCaseRace', (_message.Message,), {
  'DESCRIPTOR' : _SPECIALCASERACE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:hakuraku.SpecialCaseRace)
  })
_sym_db.RegisterMessage(SpecialCaseRace)


# @@protoc_insertion_point(module_scope)
